image: Visual Studio 2017
configuration: Release
platform:
  - x86
  - x64
cache:
  - C:\tools\vcpkg\installed\
  - C:\projects\nas2d-core\proj\vc14\packages -> proj\vc14\packages.config
before_build: nuget restore proj/vc14
build:
  project: proj/vc14/NAS2D.sln
