image: Visual Studio 2017
configuration: Release
platform:
  - x86
  - x64
before_build: nuget restore proj/vc14
build:
  project: proj/vc14/NAS2D.sln
init:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
