image: Visual Studio 2019 Preview
configuration: Release
platform:
  - x86
  - x64
cache:
  - C:\tools\vcpkg\installed\
  - C:\projects\nas2d-core\proj\vs2019\packages -> proj\vs2019\packages.config
install:
  - vcpkg integrate install
  - vcpkg install physfs:%PLATFORM%-windows
  - vcpkg install glew:%PLATFORM%-windows
  - vcpkg install gtest:%PLATFORM%-windows
  - nuget restore proj/vs2019
build:
  project: proj/vs2019/NAS2D.sln
test_script:
  - cd %APPVEYOR_BUILD_FOLDER%\test
  - '%APPVEYOR_BUILD_FOLDER%\test\%PLATFORM%\%CONFIGURATION%\test.exe'
