
language: cpp

sudo: false

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
    - libsdl2-dev
    - libsdl2-mixer-dev
    - libsdl2-image-dev
    - libsdl2-ttf-dev
    - libglew-dev
    - glee-dev
    - libphysfs-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install sdl2 sdl2_image sdl2_mixer sdl2_ttf glew physfs; fi

script:
  - make -k   # Use -k to continue after errors. This will allow more errors to be caught and listed in the logs

notifications:
  email: false
