version: 2.1

commands:
  brew-install:
    description: "Brew install MacOS dependencies (or restore from cache)"
    steps:
      - run: make install-dependencies
  build-and-test:
    steps:
      - run: make --keep-going --jobs 16 CXXFLAGS_EXTRA="-Werror"
      - run: make --keep-going --jobs 16 CXXFLAGS_EXTRA="-Werror" test
      - run: make --keep-going --jobs 16 CXXFLAGS_EXTRA="-Werror" check
      - run: make --keep-going --jobs 16 CXXFLAGS_EXTRA="-Werror" test-graphics
      - run: make package
      - store_artifacts:
          path: .build/package/

jobs:
  build-macos:
    macos:
      xcode: "13.4.1"
    environment:
      - HOMEBREW_NO_AUTO_UPDATE: 1
      - WARN_EXTRA: "-isystem /usr/local/include"
    steps:
      - checkout
      - brew-install
      - build-and-test
  build-linux-gcc:
    docker:
      - image: outpostuniverse/nas2d-gcc:1.4
    environment:
      - WARN_EXTRA: "-Wduplicated-cond -Wduplicated-branches -Wlogical-op -Wuseless-cast -Weffc++"
    steps:
      - checkout
      - build-and-test
  build-linux-clang:
    docker:
      - image: outpostuniverse/nas2d-clang:1.3
    environment:
      - WARN_EXTRA: "-Wdocumentation -Wdocumentation-unknown-command -Wcomma -Winconsistent-missing-destructor-override -Wmissing-prototypes -Wctad-maybe-unsupported"
    steps:
      - checkout
      - build-and-test
  build-linux-mingw:
    docker:
      - image: outpostuniverse/nas2d-mingw:1.8
    environment:
      - WARN_EXTRA: "-Wno-redundant-decls"
    steps:
      - checkout
      - build-and-test

workflows:
  build_and_test:
    jobs:
      - build-macos
      - build-linux-gcc
      - build-linux-clang
      - build-linux-mingw
