version: 2.1
executors:
  docker-executor:
    docker:
      - image: outpostuniverse/nas2d-circleci:1.1
  macos-executor:
    macos:
      xcode: "10.0.0"
commands:
  brew-install:
    description: "Brew install MacOS dependencies (or restore from cache)"
    steps:
      - restore_cache:
          name: Restoring brew dependencies
          key: deps-v2-NAS2D-{{ arch }}
      - run: HOMEBREW_NO_AUTO_UPDATE=1 brew install cmake physfs sdl2 sdl2_image sdl2_mixer sdl2_ttf glew
      - save_cache:
          name: Caching brew dependencies
          key: deps-v2-NAS2D-{{ arch }}
          paths:
            - /Users/distiller/Library/Caches/Homebrew
            - /usr/local/Cellar
      - run: brew link physfs sdl2 sdl2_image sdl2_mixer sdl2_ttf glew
jobs:
  build-linux:
    executor: docker-executor
    steps:
      - checkout
      - run: make --keep-going
      - run: make --keep-going check
  build-macos:
    executor: macos-executor
    steps:
      - brew-install
      - checkout
      - run: make --keep-going
      - run: echo "Testing disabled" || make --keep-going check
workflows:
  build_and_test:
    jobs:
      - build-linux
      - build-macos
