version: 2.1

commands:
  brew-install:
    description: "Brew install MacOS dependencies (or restore from cache)"
    steps:
      - restore_cache:
          name: Restoring brew dependencies
          key: deps-v5-NAS2D-{{ arch }}
      - run: HOMEBREW_NO_AUTO_UPDATE=1 make install-dependencies-darwin
      - save_cache:
          name: Caching brew dependencies
          key: deps-v5-NAS2D-{{ arch }}
          paths:
            - /usr/local/Cellar
  build-and-test:
    steps:
      - run: make --keep-going --jobs CXXFLAGS_EXTRA="-Werror"
      - run: make --keep-going --jobs CXXFLAGS_EXTRA="-Werror" test
      - run: make --keep-going --jobs CXXFLAGS_EXTRA="-Werror" check
      - run: make package
      - store_artifacts:
          path: .build/package/

jobs:
  build-macos:
    macos:
      xcode: "12.4.0"
    environment:
      - WARN_EXTRA: "-Wno-double-promotion"
    steps:
      - checkout
      - brew-install
      - build-and-test
  build-linux:
    docker:
      - image: outpostuniverse/nas2d:1.4
    steps:
      - checkout
      - build-and-test
  build-linux-gcc:
    docker:
      - image: outpostuniverse/nas2d-gcc:1.3
    steps:
      - checkout
      - build-and-test
  build-linux-clang:
    docker:
      - image: outpostuniverse/nas2d-clang:1.2
    environment:
      - WARN_EXTRA: "-Wdocumentation -Wdocumentation-unknown-command -Wcomma -Winconsistent-missing-destructor-override -Wmissing-prototypes"
    steps:
      - checkout
      - build-and-test
  build-linux-mingw:
    docker:
      - image: outpostuniverse/nas2d-mingw:1.6
    environment:
      - WARN_EXTRA: "-Wno-redundant-decls"
    steps:
      - checkout
      - build-and-test

workflows:
  build_and_test:
    jobs:
      - build-macos
      - build-linux
      - build-linux-gcc
      - build-linux-clang
      - build-linux-mingw
