name: Build

on: [push]

jobs:
  windows:
    strategy:
      fail-fast: false
      matrix:
        platform: [x86, x64]
    runs-on: windows-latest
    env:
      PLATFORM: ${{ matrix.platform }}
      BUILD_CONFIGURATION: Release
      SOLUTION_FILE_PATH: .

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Restore vcpkg dependency cache
      uses: actions/cache@v3
      id: cache
      with:
        path: C:\vcpkg\installed\
        key: ${{ runner.os }}-${{ matrix.platform }}-${{ hashFiles('InstallVcpkgDeps.bat') }}

    - name: Install vcpkg dependencies
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./InstallVcpkgDeps.bat

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: |
        vcpkg integrate install
        msbuild /maxCpuCount /warnAsError /property:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

    - name: Test
      working-directory: ./test/
      run: ../.build/${{env.BUILD_CONFIGURATION}}_${{env.PLATFORM}}_test/test.exe

    - name: Package
      run: ./Package.bat "${{env.BUILD_CONFIGURATION}}" "${{matrix.platform}}"

  linux:
    strategy:
      fail-fast: false
      matrix:
        image:
        - "nas2d-arch:1.3"
    runs-on: ubuntu-latest
    container:
      image: "outpostuniverse/${{ matrix.image }}"

    steps:
    - uses: actions/checkout@v3

    - run: make --keep-going --jobs 16 CXXFLAGS_EXTRA="-Werror"
    - run: make --keep-going --jobs 16 CXXFLAGS_EXTRA="-Werror" test
    - run: make --keep-going --jobs 16 CXXFLAGS_EXTRA="-Werror" check
    - run: make --keep-going --jobs 16 CXXFLAGS_EXTRA="-Werror" test-graphics
    - run: make package
