name: Docker Build

on:
  push:
    paths:
      - ".github/workflows/dockerBuild.yml"
      - "docker/*"
  workflow_dispatch:

jobs:
  dockerBuild:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
        - "arch"
    env:
      DockerRepository: ghcr.io/${{ github.repository_owner }}

    steps:
      - uses: actions/checkout@v4

      - run: make -C docker build-image-${{ matrix.platform }}

      - name: Docker login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io --username "${{ github.repository_owner }}" --password-stdin

      - run: make -C docker push-image-${{ matrix.platform }}
