name: Docker Build

on:
  push:
    # Builds should happen on feature branches
    # Only successfully tested builds should be merged to main
    # We don't want to rebuild after testing and verifying
    branches-ignore:
      - 'main'
    paths:
      - '.github/workflows/dockerBuild.yml'
      - 'docker/*'
  workflow_dispatch:

jobs:
  dockerBuild:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
        - 'arch'
    env:
      DockerRepository: ghcr.io/${{ github.repository_owner }}

    steps:
      - uses: actions/checkout@v4

      - name: Docker build
        run: make -C docker build-image-${{ matrix.platform }}

      - name: Docker login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io --username "${{ github.repository_owner }}" --password-stdin

      - name: Docker push
        run: make -C docker push-image-${{ matrix.platform }}
